# Generated by Django 4.1.1 on 2022-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mNumber', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'auth_table',
            },
        ),
    ]
